title: "3DCGプログラミング(メタセコイア編)。"
summary: |-
  3DCGプログラミングの本です。

  3DCGとは何か、それが分からない方も多いのではないでしょうか？
  簡単に言うと、コンピュータに立体描画させることなんですが、どうやって描画させているでしょうか？
  そういった事を、説明していきます。

topics: []
published: false
price: 0
toc_depth: 2
chapters:
  - "dc3a91"
  - "859f81"
  - "52cca1"